mongox:
 image: mongo
 container_name: mongox
 volumes:
  - "/var/data/db:/data/db"
  
nodex:
 build: ./node-docker
 container_name: nodex
 enviornment:
  - MONGO_HOST=${MONGO_HOST}
 ports: 
  - "3000:3000"

nginx-server:
 restart: always
 build: ./wb-nginx
 container_name: nginx-server
 volumes:
  - "./wb-nginx/public-html:/usr/share/nginx/html"
 ports: 
  - "80:80"
  - "443:443"
